"""empty message

Revision ID: 239eb73656b3
Revises: 744faedf2483
Create Date: 2021-03-26 06:17:26.780554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239eb73656b3'
down_revision = '744faedf2483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('add_item_category_id_fkey', 'add_item', type_='foreignkey')
    op.drop_constraint('add_item_brand_id_fkey', 'add_item', type_='foreignkey')
    op.drop_column('add_item', 'category_id')
    op.drop_column('add_item', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add_item', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('add_item', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('add_item_brand_id_fkey', 'add_item', 'brand', ['brand_id'], ['id'])
    op.create_foreign_key('add_item_category_id_fkey', 'add_item', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
