"""empty message

Revision ID: 299c408716ea
Revises: 8fd2eb9f218f
Create Date: 2021-03-26 01:16:42.413209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299c408716ea'
down_revision = '8fd2eb9f218f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profile')
    # ### end Alembic commands ###
