"""empty message

Revision ID: e93e653c9109
Revises: 299c408716ea
Create Date: 2021-03-26 01:28:32.077704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93e653c9109'
down_revision = '299c408716ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
